# 服务器配置
server:
  # 服务器端口
  port: 8080
  # 会话超时时间
  servlet:
    session:
      timeout: 30m

spring:
  # 数据配置
  datasource:
    url: jdbc:mysql://localhost:${spring.datasource.port}/${spring.datasource.database}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库名
    database: api
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
    # 端口
    port: 3306

  flyway:
    enabled: true
    baseline-on-migrate: true